
Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 45, in <module>
    guessing_game()
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 38, in guessing_game
    keepGoing = input("That's not correct. Do you want to guess again? Enter Y or N: ").strip().upper()
EOFError: EOF when reading a line

Timestamp: 2024-10-15 21:52:46.280115

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 45, in <module>
    guessing_game()
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 38, in guessing_game
    keepGoing = input("That's not correct. Do you want to guess again? Enter Y or N: ").strip().upper()
EOFError: EOF when reading a line

Timestamp: 2024-10-15 21:52:46.280252

Status: FAILED!
Check: 2
Test: The program prompts the user to try again for incorrect input.
Reason: Unable to find '['Number must be in the range of 1 to 10: Please try again:']' in the program's output.
Do you want to guess a number? Enter Y or N: I'm thinking of a number...
Try to guess by entering a number between 1 and 1000: Invalid input. Please enter a number between 1 and 1000: That's not correct. Do you want to guess again? Enter Y or N: Invalid input. Please enter Y or N: .
Error : AssertionError - Unable to find Number must be in the range of 1 to 10: Please try again: in the program's output.
Timestamp: 2024-10-15 21:52:46.306513

Status: FAILED!
Check: 3
Test: The program generates a different random number for each run.
Reason: The correct number does not appear to be random.
Error : AssertionError - 
Timestamp: 2024-10-15 21:52:49.603678
