
Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 40, in <module>
    guessing_game()
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 29, in guessing_game
    keep_going = input("Do you want to guess again? Enter Y or N: ").strip().upper()
EOFError: EOF when reading a line

Timestamp: 2024-10-15 22:15:46.979843

Status: FAILED!
Reason: Unable to run GuessNumber.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 40, in <module>
    guessing_game()
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/GuessNumber.py", line 29, in guessing_game
    keep_going = input("Do you want to guess again? Enter Y or N: ").strip().upper()
EOFError: EOF when reading a line

Timestamp: 2024-10-15 22:15:46.979944

Status: FAILED!
Check: 2
Test: The program prompts the user to try again for incorrect input.
Reason: Unable to find '['Number must be in the range of 1 to 10: Please try again:']' in the program's output.
I'm thinking of a number between 1 and 10...
Try to guess by entering a number between 1 and 10: Invalid input. Please enter a valid integer.
Try to guess by entering a number between 1 and 10: Number must be in the range of 1 to 10: Please try again.
Try to guess by entering a number between 1 and 10: Number must be in the range of 1 to 10: Please try again.
Try to guess by entering a number between 1 and 10: That's not correct.
Do you want to guess again? Enter Y or N: Thank you for playing!
.
Error : AssertionError - Unable to find Number must be in the range of 1 to 10: Please try again: in the program's output.
Timestamp: 2024-10-15 22:15:46.996566

Status: PASSED!
Check: 3.2
Test: The program will eventually generate 5 as the correct answer.
Reason: None
Timestamp: 2024-10-15 22:15:47.587634

Status: PASSED!
Check: 3.4
Test: The program will eventually generate 4 as the correct answer.
Reason: None
Timestamp: 2024-10-15 22:15:47.830796

Status: PASSED!
Check: 3.1
Test: The program will eventually generate 1 as the correct answer.
Reason: None
Timestamp: 2024-10-15 22:15:48.201051

Status: PASSED!
Check: 3.3
Test: The program will eventually generate 8 as the correct answer.
Reason: None
Timestamp: 2024-10-15 22:15:48.336652
